name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
      
    - name: Debug
      run: ls
    - name: hosting
      run: |
        set -e
        yarn && yarn build
        ls 
        cd src/.vuepress/dist
        git init
        git config --global user.email "shubhamaapna@gmail.com"
        git config --global user.name "shubhamaapna"
        git branch --list
        git add -A
        git commit -m 'deploy to gh-pages branch'
        git push -f git@github.com:shubhamaapna/demopipe.git master:gh-pages
        cd -
