name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
      
    - name: Debug
      run: ls
    - name: hosting
      env:
       GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        set -e
        yarn && yarn build
        ls 
        
        export ${{ secrets.ACCESS_TOKEN }}
        cd src/.vuepress/dist
        git init
        git config --global user.email "shubhamaapna@gmail.com"
        git config --global user.name "shubhamaapna"
        git branch --list
        git add -A
        git commit -m 'deploy to gh-pages branch'
        git remote add origin https://github.com/shubhamaapna/nodejs.git
        git push -u origin


