name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
      
    - name: Debug
      run: ls
    
    - name: auth-check
      run: |
        git clone https://github.com/sanjayaapna/demopipe.git
        Username: sanjayaapna
        Password: ${{ secrets.ACCESS_TOKEN }}
            
      
#     - name: vuepress-deploy
#       uses: jenkey2011/vuepress-deploy@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         TARGET_REPO: sanjayaapna/demopipe
#         TARGET_BRANCH: develop
#         BUILD_SCRIPT: yarn && yarn build
#         BUILD_DIR: src/.vuepress/dist/
