name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: sanjayaapna/demopipe
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: src/.vuepress/dist/
