name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
      
    - name: Debug
      run: ls
      
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      with:
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        
      env:
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         TARGET_REPO: sanjayaapna/demopipe
         TARGET_BRANCH: gh-pages
         BUILD_SCRIPT: yarn && yarn build
         #BUILD_DIR: src/.vuepress/dist/
