name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
      
    - name: Debug
      run: ls
    - name: hosting
      env:
       GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        set -e
        ls 
        cd src/.vuepress/dist
        export GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}
        git config --global user.email "shubhamaapna@gmail.com"
        git config --global user.name "shubhamaapna"
        echo "==================="
        git init
        git branch --show-current
        git add -A
        git commit -m 'deploy to gh-pages branch'
        git push -f https://github.com/shubhamaapna/demopipe.git main


