name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
      
    - name: Debug
      run: ls
    - name: hosting
      env:
       GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        set -e
        yarn && yarn build
        ls 
        
        export GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}
        mkdir workenv
        cp src/.vuepress/dist workenv
        cd workenv/src/.vuepress/dist
        git config --global user.email "shubhamaapna@gmail.com"
        git config --global user.name "shubhamaapna"
        git init
        git branch --show-current
        git add -A
        git commit -m 'deploy to gh-pages branch'
        git remote add origin https://github.com/shubhamaapna/demopipe.git
        git push -f https://github.com/shubhamaapna/demopipe.git gh-pages
        cd -


