name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
      
    
    
    
    - name: GitHub Push
       # You may pin to the exact commit or the version.
       # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
    # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: $\{{ secrets.GITHUB_TOKEN }}
    # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
    # Destination branch to push changes
        branch:  gh-pages
    # Directory to change to before pushing.
        directory:  /src/.vuepress/dist
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
#     - name: Debug
#       run: ls
#     - name: hosting
#       env:
#        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#       run: |
#         set -e
#         ls 
#         cd src/.vuepress/dist
#         export GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}
#         git config --global user.email "shubhamaapna@gmail.com"
#         git config --global user.name "shubhamaapna"
#         echo "==================="
#         git init
#         git branch --show-current
#         git add -A
#         git commit -m "deploy to gh-pages branch"
#         git push -f git@github.com/shubhamaapna/demopipe.git master:gh-pages
        
